#!/usr/bin/env python3
"""Regenerates seed/responsibilities.json from the canonical audit data.
Source: Household Responsibility Audit (Google Sheets), transcribed 2026-06-09.
Verifies owner totals against the audit summary tables before writing."""
import json, re
from collections import Counter

# (category, name, p_desc, p_own, p_dod, m_desc, m_own, m_dod, e_desc, e_own, e_dod, freq, tier)
R = [
("Adult Health","Husband's medical appointments and health management","Identify needed visits, research providers, schedule","H","Appointments are booked in advance","Track upcoming visits, results, and follow-ups","H","No appointments are missed or overdue","Attend appointments and manage own health","H","Visits attended and any follow-up actioned","As needed/annual","T1_calendar"),
("Adult Health","Wife's medical appointments and health management","Identify needed visits, research providers, schedule","W","Appointments are booked in advance","Track upcoming visits, results, and follow-ups","W","No appointments are missed or overdue","Attend appointments and manage own health","W","Visits attended and any follow-up actioned","As needed/annual","T1_calendar"),
("Business","Synthminds management","Strategic planning, priorities, and direction","H","Goals and next steps are clearly defined","Track spending","H","Understanding of revenue and expenses","Execute tasks and deliverables","H","Committed work is completed on time","Ongoing","T3_human_capture"),
("Cleaning and Tidying","Deep cleaning coordination","Coordinate cleaners and schedule, ensure sheets laundered and placed, ensure funds available, write check","W","Cleaners are booked on recurring schedule","Track cleaning cycle","W","Next appointment is always confirmed","Cleaners handle execution biweekly","O","Cleaners complete their visit","Biweekly","T1_calendar"),
("Cleaning and Tidying","General tidying","Decide what needs to be reset","W","Expectations are shared","Notice clutter","W","Messes are flagged before they accumulate","Tidy throughout the day","S","Main areas are clear by end of day","Daily","T3_human_capture"),
("Cleaning and Tidying","Nightly resets","Set the standard for what done looks like","W","Both partners agree on what reset means","Notice what is left undone","W","Incomplete areas are caught before bed","Reset kitchen, living room, dining room, front hall, playroom","S","All areas are clear before bed","Nightly","T3_human_capture"),
("Cleaning and Tidying","Trash and recycling","Know collection timing","H","Collection days are known","Notice when bins are full","S","Bins checked before overflow","Take out trash, recycling, break down boxes","H","Bins are out on time and not overflowing","Weekly + as needed","T2_state"),
("Cleaning and Tidying","Vacuuming and floor cleanup","Determine when needed","S","Frequency is agreed","Notice dirt and debris","S","Floors are checked proactively","Vacuum or sweep","S","Floors are visibly clean","As needed","T3_human_capture"),
("Daughter Activities","Dance","Register, plan weekly clothing readiness","W","Registration complete and clothing system in place","Ensure daughter has correct clothes and is ready","W","Outfit is confirmed ready before Monday","Transport daughter on Mondays and present during class","H","Daughter is participating in dance and home safely","Weekly","T1_calendar"),
("Daughter Clothing","Clothing management","Shop, size up, rotate by season","W","Seasonal review is completed","Notice what no longer fits or needs replacing","W","Gaps are identified before daughter runs short","Buy, organize, wash, put away","W","Clothes are accessible and in good condition","Weekly + seasonal","T3_human_capture"),
("Daughter Daily Care","Bedtime","Maintain bedtime structure and routine","W","Routine is agreed and consistent","Keep timing consistent","W","Bedtime starts at agreed time without reminders","Lead bedtime routine","S","Child is in bed NLT 9pm","Daily","T1_calendar"),
("Daughter Daily Care","Lunches and snacks","Plan food for school week","W","A lunch/snack plan exists for the week","Ensure food is stocked and ready to pack","W","All needed items are available the night before","Pack lunch and snack each morning","W","Bag is packed before departure","Daily school days","T2_state"),
("Daughter Daily Care","School drop-off","Coordinate timing with work schedules","W","Coverage is confirmed for the day","Track who is available; adjust as needed","W","Both parents know the plan before school day starts","Handle drop-off","W","Daughter is safely dropped off before 9am","Most school days","T1_calendar"),
("Daughter Daily Care","School morning routine","Decide what daughter needs each day (specials, weather, clothing, assignments)","W","All items for the day are identified before morning begins","Check schedule, lunch readiness, library books, sneakers, assignments","W","All items confirmed ready the night before or by 7am","Wake daughter, get ready, feed breakfast, vitamins, pack bags","W","Daughter leaves on time with everything needed","Daily school days","T1_calendar"),
("Daughter Daily Care","School pick-up","Coordinate timing with work schedules","W","Coverage is confirmed for the day","Track who is available; adjust as needed","W","Both parents know the plan before school day starts","Handle pick-up","S","Daughter is safely picked up on time before 3:30pm","Most school days","T1_calendar"),
("Daughter Daily Care","Shower support","Determine when support is needed","W","Cadence is agreed","Notice when it is due","W","Shower happens without needing to be requested","Assist daughter with shower","S","Shower is completed","Weekly/as needed","T1_calendar"),
("Daughter Health","Daughter appointments","Identify needed visits and schedule","W","Appointments are booked in advance","Track upcoming visits","W","All visits are on calendar","Make appointments and take daughter","W","Appointment attended and any follow-up noted","As needed","T1_calendar"),
("Daughter School Admin","Field trips","Sign up, complete forms, add to calendar","W","Forms submitted and trip is on calendar","Track details and communicate with the other parent","W","Attending parent has all details in advance","Attend field trip (outdoor: Wes, indoor: Ria)","S","Parent attends as planned","As needed","T1_calendar"),
("Daughter School Admin","School forms and deadlines","Review forms and plan submissions","W","All upcoming deadlines are known","Track deadlines and calendar entries","W","Deadlines are on calendar with reminders","Submit forms and registrations","W","All forms submitted by deadline","Ongoing","T1_calendar"),
("Daughter School Admin","School pick-up backup plan","Identify backup options and communicate with contacts","W","At least one reliable backup is confirmed","Track availability of backups and flag gaps","W","Backup is confirmed before it is needed","Coordinate and arrange backup pick-up when needed","W","Daughter is picked up safely by the agreed backup","As needed","T1_calendar"),
("Daughter Social","Birthday parties, gifts, RSVPs, thank-you notes","Plan gifts, RSVPs, cards","W","Gifts planned and RSVPs sent on time","Track deadlines and follow-through","W","No deadlines are missed","Complete tasks with daughter","W","Gift given and thank-you note sent","As needed","T1_calendar"),
("Daughter Social","Daughter playdates","Listen to daughter, reach out to parents for scheduling, update calendar","W","Planned, on calendar, activity/location selected","Track playdates and schedule/weather changes","W","No deadlines are missed","Playdate with friend","S","Playdate is complete","As needed","T1_calendar"),
("Dog Care","Dog feeding","Determine feeding schedule","W","Schedule is agreed and clear","Notice whether it has been done","W","Feeding is confirmed each morning","Feed dog each morning","S","Dog is fed at consistent time","Daily","T1_calendar"),
("Dog Care","Dog food/treats/Rx ordering","Determine reorder needs","W","Reorder threshold is set","Track inventory levels","W","Order placed before running out","Place orders for food, treats, meds","W","Order arrives before stock depletes","Monthly/as needed","T2_state"),
("Dog Care","Dog medications","Know what meds are needed and when","S","Medication schedule is documented","Track supply and schedule","S","Meds are reordered before running out","Administer meds","S","Meds given on schedule","Daily/as prescribed","T2_state"),
("Dog Care","Dog waste cleanup outside","Set cleanup cadence","H","Frequency is agreed","Notice when yard needs attention","S","Yard is checked proactively","Clean up yard","H","Yard cleared at least 2-3x per week","2-3x weekly","T1_calendar"),
("Dog Care","Grooming appointments","Identify when grooming is due","S","Grooming cadence is set","Track schedule","S","Appointment booked in advance","Schedule and take dog","H","Dog groomed on schedule","As needed","T1_calendar"),
("Dog Care","Vet appointments","Identify when visits are needed","H","Visit cadence is understood","Track schedule and Rx renewals","S","Appointments are on calendar","Schedule and take dog","H","Appointment attended and Rx renewed if needed","As needed","T1_calendar"),
("Emergency Preparedness","Emergency preparedness","Research and plan supplies, systems, and scenarios","S","A prep plan is documented and agreed","Track inventory, expiry dates, and gaps","H","Supplies are checked and updated regularly","Purchase, store, and maintain supplies","H","Supplies are stocked and organized","Ongoing/as needed","T2_state"),
("Extended Family","Extended family visits - hosting","Plan visit timing, logistics, sleeping arrangements, activities","W","Visit is planned and confirmed in advance","Track RSVPs, dietary needs, and prep tasks","W","All details are known before guests arrive","Host, cook, clean, and coordinate during visit","S","Guests are welcomed and visit runs smoothly","As needed","T3_human_capture"),
("Extended Family","Physical labor support - wife's parents' house","Identify tasks and coordinate timing","S","Task list and schedule are agreed in advance","Track what needs doing and when","S","Upcoming tasks are flagged before they become urgent","Complete physical labor tasks","H","Tasks are completed as agreed","As needed","T3_human_capture"),
("Home Maintenance","Repairs and property manager coordination","Identify issues and coordinate repair path","S","Issue is logged and next step is clear","Follow up to ensure completion","S","Repair is completed without repeated reminders","Handle repairs or liaise with property manager","H","Issue is resolved and closed","As needed","T3_human_capture"),
("Home and Tech","Home furniture - ordering and assembly","Research, select, and plan furniture purchases","S","Options are reviewed and decision is made","Track delivery timelines and what is still needed","S","Deliveries are confirmed and gaps noted","Assemble and place furniture","H","Furniture is assembled and in place","As needed","T3_human_capture"),
("Home and Tech","Home wi-fi and tech infrastructure","Research and decide on routers, devices, and systems","H","Tech needs are assessed and a plan is in place","Track performance, outages, and upgrade needs","H","Issues are noticed and addressed proactively","Set up, maintain, and troubleshoot home tech","H","Wi-fi and devices are working reliably","Ongoing/as needed","T3_human_capture"),
("Home and Tech","Researching home electronics and cars","Research options, compare, and recommend","H","Research is complete before a purchase decision is needed","Track what needs replacing or upgrading","S","Upcoming needs are flagged in advance","Make final decision and purchase","S","Purchase is made based on research","As needed","T3_human_capture"),
("Household Admin","Bills and finances","Manage bills and financial flow","W","Payment schedule is organized","Track due dates and spending","W","All due dates are on calendar","Pay bills and manage accounts","W","All bills paid on time","Monthly","T1_calendar"),
("Household Admin","Camp signup","Research options and decide","S","Options are reviewed and decision made","Track deadlines","S","Signup deadlines are on calendar","Complete registration","H","Registration submitted on time","Seasonal","T1_calendar"),
("Household Admin","Daughter's digital life - screen time, apps, parental controls","Set rules, research tools, and configure systems","S","Expectations and controls are agreed and in place","Track usage patterns and flag issues","S","Screen time and content are regularly reviewed","Enforce limits and adjust settings as needed","S","Controls are working and daughter understands expectations","Ongoing","T1_calendar"),
("Household Admin","Dog insurance claims","Know when a claim is eligible","H","Eligibility is understood","Track outstanding submissions","S","All eligible claims are submitted","Submit claims","H","Claims submitted within the eligible window","As needed","T1_calendar"),
("Household Admin","Household supplies","Determine what is needed","S","Supply needs are reviewed regularly","Track inventory","S","Gaps noticed before running out","Purchase supplies","S","Supplies restocked before they run out","Weekly/as needed","T2_state"),
("Household Admin","Overall family calendar","Maintain events, activities, obligations","W","All known events are entered","Track conflicts and upcoming logistics","W","Conflicts flagged and resolved in advance","Update and manage calendar","W","Calendar is current and accessible to both","Daily/weekly","T1_calendar"),
("Household Admin","School deadlines","Review notices and plan submissions","W","All upcoming deadlines are identified","Track dates","W","Deadlines are on calendar with buffer","Complete forms and tasks","W","All submitted on time","Ongoing","T1_calendar"),
("Household Admin","Subscription and membership management","Decide which subscriptions and memberships to keep or add","S","Subscriptions are reviewed and intentional","Track renewal dates, costs, and usage","S","No subscription renews unnoticed","Cancel, renew, or update subscriptions","S","All subscriptions are current and intentional","Ongoing/monthly","T1_calendar"),
("Household Admin","Taxes","Identify what is needed each year","S","Documents are gathered in advance","Track deadlines","S","Filing deadline is on calendar","Complete and file taxes","H","Taxes filed on time","Annual","T1_calendar"),
("Insurance","Home and car insurance renewals","Review coverage needs and research options at renewal","H","Coverage is reviewed before renewal deadline","Track renewal dates and flag changes in coverage or cost","H","No renewal is missed or auto-renewed without review","Renew or switch policies and update records","H","Policies are current and confirmed","Annual/as needed","T1_calendar"),
("Laundry","Bath mats","Determine cadence","W","Frequency is agreed","Track when due","W","Mats washed within the cycle","Wash, dry, put away","W","Clean bath mats are in place","Monthly","T1_calendar"),
("Laundry","Daughter laundry","Determine schedule","W","Cadence is agreed","Track when basket is full and what is needed","W","Laundry done before daughter runs short","Wash, dry, fold, put away","W","Clothes are clean and put away","Weekly","T1_calendar"),
("Laundry","Husband laundry","Determine schedule","H","Cadence is set","Track when needed","H","Laundry done before running low","Wash, dry, fold, put away","H","Clothes are clean and put away","Weekly","T1_calendar"),
("Laundry","Kitchen towels","Determine cadence","W","Frequency is agreed","Track when due","W","Towels washed within the cycle","Wash, dry, put away","W","Clean kitchen towels are available","Every 2 weeks","T1_calendar"),
("Laundry","Regular towels","Determine cadence","W","Frequency is agreed","Track when due","W","Towels washed within the cycle","Wash, dry, put away","W","Clean towels are available","Every 2 weeks","T1_calendar"),
("Laundry","Sheets (3 beds)","Determine cadence","W","Frequency is agreed for all beds","Track when due","W","Sheets are washed within the cycle","Wash, dry, remake beds","W","All beds are made with clean sheets","Every 2 weeks","T1_calendar"),
("Laundry","Wife laundry","Determine schedule","W","Cadence is set","Track when needed","W","Laundry done before running low","Wash, dry, fold, put away","W","Clothes are clean and put away","Weekly","T1_calendar"),
("Meals and Kitchen","Dishwasher loading/unloading","Set standard for when to run it","H","Timing expectation is clear","Ensure dishes are clean in time for morning","S","Lunchbox and water bottle are clean before bed","Load and unload dishwasher","H","Dishwasher is run and unloaded before morning","Daily","T1_calendar"),
("Meals and Kitchen","Family meal quality and nutrition","Decide what the family should be eating","W","A general nutrition approach is agreed","Notice patterns and timing","W","Issues flagged before they become habits","Maintain meal regularity","W","Meals are consistent and balanced","Daily/weekly","T3_human_capture"),
("Meals and Kitchen","Kitchen reset","Set standard for nightly reset","S","Standard is agreed and visible","Notice what is left undone","S","Gaps caught before going to bed","Reset kitchen each night","H","Counters clear, dishes handled, surfaces ready","Nightly","T3_human_capture"),
("Meals and Kitchen","Takeout/ordering in","Decide when takeout makes sense","S","Decision is made proactively, not reactively","Notice when a meal plan gap exists","S","Gap is caught before everyone is hungry","Order and pick up or receive","S","Food arrives without chaos","As needed","T3_human_capture"),
("Meals and Kitchen","Weekly groceries","Make list, plan meals and snacks","W","List is complete before shopping","Track what is running low","W","Gaps noticed before they cause a problem","Shop and put groceries away","W","Food is purchased and put away before needed","Weekly","T2_state"),
("Meals and Kitchen","Weeknight meals","Decide meals and needed ingredients","W","Plan is set before shopping","Ensure food is available","W","All ingredients are on hand","Cook dinner","W","Dinner is served at a reasonable time","Most weekdays","T2_state"),
("Outdoor and Vehicles","Annual weeding","Determine timing and scope","H","Weeding plan is set at start of season","Track when weeding is due","H","Timing is noted and acted on proactively","Complete weeding","H","All beds are weeded within the agreed window","Annual","T1_calendar"),
("Outdoor and Vehicles","Car cleaning - Subaru Ascent","Determine cleaning schedule and standards","W","Cleaning cadence is agreed","Track when cleaning is due","W","Car is noticed and flagged before it becomes overdue","Clean car inside and out","H","Car is visibly clean inside and out","As needed","T3_human_capture"),
("Outdoor and Vehicles","Car servicing and cleaning - electric car","Determine service and cleaning needs","H","Service intervals and cleaning cadence are tracked","Track service intervals and cleaning schedule","H","No service or cleaning is overdue","Service and clean car","H","Car is serviced and clean on schedule","As needed/ongoing","T1_calendar"),
("Outdoor and Vehicles","Car servicing - both cars","Determine service needs for both vehicles","H","Service intervals are tracked for both cars","Track mileage and upcoming service appointments","H","No service is overdue","Book and take cars for service","H","Both cars serviced on schedule","Ongoing/as needed","T1_calendar"),
("Outdoor and Vehicles","Gardener/lawn support coordination","Research, hire, and schedule lawn/garden support","W","Gardener is booked and scope is agreed","Coordinate appointments and communicate scope","W","Gardener has clear direction before each visit","Liaise with gardener; oversee work","W","Work is completed as expected","Seasonal/ongoing","T1_calendar"),
("Outdoor and Vehicles","Snow plowing","Arrange plowing service or plan for removal","H","Plan is in place before first snow","Monitor weather and ensure driveway is clear","H","Driveway is checked after each snowfall","Coordinate or carry out snow removal","H","Driveway is passable without delay","As needed/winter","T1_calendar"),
("Relationship","Couple therapy","Research therapists, schedule sessions, manage logistics","W","Therapist is booked and sessions are on the calendar","Track upcoming sessions, reschedules, and continuity","W","No sessions are missed or forgotten without notice","Attend sessions and engage in the work","S","Both partners attend and participate","Recurring","T1_calendar"),
("Relationship","Date night and couple time","Decide on activities, timing, and logistics","T","A plan is made proactively rather than reactively","Track when time together last happened and when next is planned","T","Couple time is a recurring item, not an afterthought","Make reservations, arrange childcare, follow through","T","Date or intentional time together actually happens","Recurring","T1_calendar"),
("Social and Holidays","Family outings and dinners out","Decide options and coordinate timing","W","Outing is planned in advance","Track availability","W","Timing confirmed with all family members","Reserve and plan","W","Reservation made and plan confirmed","Recurring","T1_calendar"),
("Social and Holidays","Gifts for family","Decide what to buy and for whom","S","Gift list is prepared ahead of occasions","Track occasions and deadlines","S","All upcoming occasions are on calendar","Buy and manage gifts","S","Gifts purchased and ready before the occasion","Year-round","T1_calendar"),
("Social and Holidays","Holidays","Plan logistics, expectations, and gifts","W","Plan is set well in advance","Track everything that must happen","W","All tasks are on a list with owners","Execute the plan","W","Holiday happens as planned","Seasonal","T1_calendar"),
("Social and Holidays","Social events with friends","Decide dates and initiate plans","W","Plans are initiated proactively","Track RSVPs and follow-through","W","All logistics confirmed","Plan and organize","W","Event happens as planned","Ongoing","T1_calendar"),
("Social and Holidays","Teacher gifts/cards","Plan for key moments (Christmas, end of year)","W","Gifts/cards planned ahead of deadline","Track deadlines","W","Deadlines are on calendar","Buy and prepare","W","Gift/card ready before last school day","Seasonal","T1_calendar"),
("Social and Holidays","Vacation and travel planning","Research destinations, options, and timing","S","A shortlist of options is ready to decide from","Track booking deadlines, documents, and logistics","S","All bookings and prep are confirmed in advance","Book flights, accommodation, and activities","S","All travel is booked and itinerary is ready","As needed/annual","T1_calendar"),
]

OWNER = {"W":"ria","H":"wes","S":"shared","O":"outsource","T":"tbd"}
def slug(n): return re.sub(r'[^a-z0-9]+','-',n.lower()).strip('-')[:48]

rows = []
for i,(cat,name,pd,po,pdod,md,mo,mdod,ed,eo,edod,freq,tier) in enumerate(R,1):
    rows.append({
      "id": f"resp-{i:03d}-{slug(name)}",
      "category": cat, "name": name,
      "planning":   {"description": pd, "owner": "wisp", "owner_legacy": OWNER[po], "definition_of_done": pdod},
      "monitoring": {"description": md, "owner": "wisp", "owner_legacy": OWNER[mo], "definition_of_done": mdod},
      "execution":  {"description": ed, "owner": OWNER[eo], "definition_of_done": edod},
      "frequency": freq, "monitoring_tier": tier, "status": "active"
    })

pl = Counter(r["planning"]["owner_legacy"] for r in rows)
ml = Counter(r["monitoring"]["owner_legacy"] for r in rows)
assert len(rows)==72, len(rows)
assert (pl["ria"],pl["wes"],pl["shared"],pl["tbd"])==(40,15,16,1), pl
assert (ml["ria"],ml["wes"],ml["shared"],ml["tbd"])==(40,10,21,1), ml

out = {"_meta":{"source":"Household Responsibility Audit (Google Sheets), seeded 2026-06-09",
  "ownership_rule":"All planning.owner and monitoring.owner flipped to 'wisp' per the P/M/E contract; human owners preserved in owner_legacy for the day-90 re-audit. execution.owner imported as-is and MUST stay human.",
  "tiers":{"T1_calendar":"deterministic cron checks","T2_state":"consumption/threshold models + capture","T3_human_capture":"humans see, Wisp routes"}},
  "responsibilities": rows}
json.dump(out, open("seed/responsibilities.json","w"), indent=2)
print(f"OK: 72 rows verified, tiers: {dict(Counter(r['monitoring_tier'] for r in rows))}")
